version: 2

updates:
  # Dépendances npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"

  # Actions GitHub
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
